from PyQt5.QtWidgets import *

app = QApplication([])
window = QWidget()
window.resize(800, 600)

list1 = QListWidget()
list2 = QListWidget()
CreatNodeBtn = QPushButton("Створити замітку")
DelNodeBtn = QPushButton("Видалити замітку")
SaveNodeBtn = QPushButton("Зберегти замітку")
searchline = QLineEdit("Введіть тег...")
AddNodeBtn = QPushButton("додати до заміток")
UnPinNodeBtn = QPushButton("Відкріпити від замітки")
SearchTag = QPushButton("Шукати звмітку по тегу")
mainline = QHBoxLayout()
V1line = QVBoxLayout()
V2line = QVBoxLayout()
V1line.addWidget(QTextEdit())
mainline.addLayout(V1line)
V2line.addWidget(QLabel("Список заміток"))
V2line.addWidget(list1)
btn1vline = QVBoxLayout()
btn1hline = QHBoxLayout()
btn1hline.addWidget(CreatNodeBtn)
btn1hline.addWidget(DelNodeBtn)
btn1vline.addLayout(btn1hline)
btn1vline.addWidget(SaveNodeBtn)
V2line.addLayout(btn1vline)
V2line.addWidget(QLabel("Список Тегів"))
V2line.addWidget(list2)
V2line.addWidget(searchline)
btn2vline = QVBoxLayout()
btn2hline = QHBoxLayout()
btn2hline.addWidget(AddNodeBtn)
btn2hline.addWidget(UnPinNodeBtn)
btn2vline.addLayout(btn2hline)
btn2vline.addWidget(SearchTag)
V2line.addLayout(btn2vline)
mainline.addLayout(V2line)

window.setLayout(mainline)
window.show()
app.exec()
